name: Automate POST Request to Render URL

on:
  schedule:
    - cron: "*/10 * * * *" 

jobs:
  send-post-request:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Send POST to Render App
        run: |
          curl -X POST https://agenticmeetingscheduler.onrender.com/process-cron \
          -H "Content-Type: application/json" \
          --max-time 300 # Timeout for the curl command (300 seconds)
